services:
  - type: web
    name: nova-cv
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn nova_cv.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "127.0.0.1,localhost,nova-cv.onrender.com"
      - key: EMAIL_USER
        value: "divin3448@gmail.com"
      - key: EMAIL_PASSWORD
        value: "dooe qlvd hyfc sppd"
