# Generated by Django 5.1.5 on 2025-05-03 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='numero_transaction',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='commande',
            name='produit',
            field=models.CharField(max_length=255),
        ),
    ]
