# Generated by Django 5.1.5 on 2025-05-03 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_alter_commande_numero_transaction_and_more'),
    ]

    operations = [
    ]
