# Generated by Django 5.1.5 on 2025-05-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_auto_20250503_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='telephone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
