# Generated by Django 5.1.5 on 2025-05-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0004_commande_nom_commande_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
