# Generated by Django 5.1.5 on 2025-05-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0007_reponsefeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(choices=[('CV_SIMPLE', 'CV Simple'), ('CV_BASIQUE', 'CV Numérique Basique'), ('CV_AVANCE', 'CV Numérique Avancé'), ('CV_SITE', 'CV + Site Vitrine')], max_length=20)),
                ('prix', models.PositiveIntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mode', models.CharField(max_length=15)),
                ('transaction', models.CharField(max_length=100, unique=True)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('FAILED', 'Échoué')], default='PENDING', max_length=10)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
