# Generated by Django 5.1.5 on 2025-05-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0008_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionValide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operateur', models.CharField(choices=[('MTN', 'MTN Money'), ('AIRTEL', 'Airtel Money')], max_length=10)),
                ('numero_transaction', models.CharField(max_length=100, unique=True)),
                ('montant', models.PositiveIntegerField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
