# Generated by Django 5.1.5 on 2025-05-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0009_transactionvalide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mode',
            field=models.CharField(choices=[('AIRTEL', 'Airtel Money'), ('MTN', 'MTN Money')], max_length=15),
        ),
    ]
