# Generated by Django 5.1.5 on 2025-06-02 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0010_alter_order_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Commande',
        ),
    ]
