# Generated by Django 5.1.5 on 2025-06-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0011_smsreceived_delete_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepotExterieur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_transaction', models.CharField(max_length=100, unique=True)),
                ('montant', models.IntegerField()),
                ('operateur', models.CharField(max_length=20)),
                ('expediteur', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
