# Generated by Django 5.1.5 on 2025-06-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0012_depotexterieur'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsValide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_transaction', models.CharField(max_length=100, unique=True)),
                ('montant', models.FloatField()),
                ('operateur', models.CharField(max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DepotExterieur',
        ),
        migrations.DeleteModel(
            name='SmsReceived',
        ),
        migrations.DeleteModel(
            name='TransactionValide',
        ),
    ]
